name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job_1:
    build:
      name: Linux_Build
      runs-on: ubuntu-latest

      steps:
      - id: step1
      - uses: actions/checkout@v2
      - name: make
          run: make linux
    
  job_2:
    build:
      name: Windows_build  
      runs-on: ubuntu-latest

      steps:
      - id: step1
      - uses: actions/checkout@v2
      - name: make
          run: make windows

