name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install_dependency
      run: sudo apt install mingw-w64

    - name: check_out
      uses: actions/checkout@v2
    
    - name: make
      run: make all
    
      
