name: Master Workflow

on:
  push:
    branches: [ master ]



jobs:
  create_release:
  
    runs-on: ubuntu-latest

    steps:

    - name: Install dependency 
      id: install_dependency
      run: sudo apt install mingw-w64

    - name: Check Out
      id: check_out
      uses: actions/checkout@v2
    
    - name: Make
      id: make
      run: make all

    - name: Consolidate
      run: | 
      
        mkdir Release
        mv build_linux/tictactoe.out Release/tictactoe.out
        mv build_windows/tictactoe.exe Release/tictactoe.exe

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false

    - name: Upload Asset Linux
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: Release/tictactoe.out
        asset_name: tictactoe.out
        asset_content_type: application
    
    - name: Upload Asset Windows
      id: upload-release-asset-windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Release/tictactoe.exe
        asset_name: tictactoe.exe
        asset_content_type: application