name: PR Workflow

on:
  pull_request:
    branches: [ master ]



jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      # install the following dependencies
      # 1. windows cross compiler
      # 2. cppcheck
      - name: Install dependencies
        id: install_dependencies
        run: |

          sudo apt install mingw-w64
          sudo apt-get install cppcheck

          # Add Docker's official GPG key:
          sudo apt-get update
          sudo apt install -y apt-transport-https ca-certificates curl gnupg
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/dockerce.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/dockerce.gpg] https://download.docker.com/linux/ubuntu jammy stable" | sudo tee /etc/apt/sources.list.d/dockerce.list > /dev/null
          sudo apt update
          sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Check Out
        id: check_out
        uses: actions/checkout@v2

      - name: Make
        id: make
        run: make all

      - name: Lint
        id: lint
        run: make lint

      - name: Upload Linux Binary
        id: upload_linux_binary
        uses: actions/upload-artifact@v2
        with: 
          name: Linux_Binary
          path: bin/build_linux/tictactoe.out

      - name: Upload Windows EXE
        id: upload_windows_exe
        uses: actions/upload-artifact@v2
        with:
          name: Windows_EXE
          path: bin/build_windows/tictactoe.exe

  test_on_ubuntu:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Binary
        id: download_binary
        uses: actions/download-artifact@v2
        with:
          name: Linux_Binary

      - name: Granting Permissions
        id: granting_permission
        run: chmod +x tictactoe.out
      
      - name: Run Binary
        id: run_binary
        run: ./tictactoe.out 2 1 1

  test_on_windows:

    runs-on: windows-latest
    needs: build
    steps:
      - name: Download EXE
        id: download_exe
        uses: actions/download-artifact@v2
        with:
          name: Windows_EXE
      
      - name: Run EXE
        id: run_exe
        run: .\tictactoe.exe 2 1 1
